### ISSUE TITLE
Feature: Azure Video Indexer

### ISSUE THREAD

**Issue by parithon** [builders-club/number-one#10]
Use the [Azure Video Indexer](https://azure.microsoft.com/en-us/services/media-services/video-indexer/) to gather analytics from the videos generated by users.

> Video Indexer enables you to extract, review, curate, customize, search and publish insights from your videos using AI for video technologies, powered by Azure Media Services. Video Indexer can be used above the demo experience threshold by connecting it with an Azure Media Services account.

**Comment by MichaelJolley** [comment]
@all-contributors please add @parithon for ideas

**Comment by MichaelJolley** [comment]
Thanks for the input! I'm closing this issue since we aren't adding the video portion of the project anymore.
