### ISSUE TITLE
A couple of bugs

### ISSUE THREAD

**Issue by cmjchrisjones** [builders-club/number-one#103]
~~1 - Audio files stepping on each other - not queueing up~~ tracked by #105 
~~2- Stop command not firing properly~~ tracked by #104 
3 - Some SFX's are missing (bennyhill, canttouchthis, plus maybe some more) - this issue - closing as not a bug as per below comment - won't fix
~~4 - !help isn't firing~~ tracked by #106

**Comment by MichaelJolley** [comment]
Disregard 3 above. I removed them for DMCA
