### ISSUE TITLE
!hardware command does not show hardware

### ISSUE THREAD

**Issue by barranger** [builders-club/number-one#118]
**Describe the bug**

**To Reproduce**
1. Go to stream chat
2. type !hardware
3. The bot comments "We done did the do"

**Expected behavior**
the bot should comment the actual hardware

**Comment by MichaelJolley** [comment]
Yeah this is a new command. I reckon we can say:

```
The stream uses: Gb X570 AORUS Elite, AMD Ryzen 9 3950X, 64G RAM, GeForce RTX 2080 Super, 2x Sony A6400, Shure SM7B, GoXLR and a plethora of lights. 
```
