### ISSUE TITLE
Where to get Twitch authentication from?

### ISSUE THREAD

**Issue by exegete46** [builders-club/number-one#25]
**Is your feature request related to a problem? Please describe.**
When setting up the bot, there is not direct documentation for how to get the `TWITCH_CLIENT_ID`, `TWITCH_CLIENT_SECRET`, and `TWITCH_BOT_AUTH_TOKEN`.  For folks just starting out it would be helpful to have this documented.

**Describe the solution you'd like**
Add documentation on where to find the values for the more esoteric environment variables.

**Comment by MichaelJolley** [comment]
@exegete46 thanks for contributing.

Check out the existing docs in our `dev` branch.  I think they cover what you're looking for.

https://github.com/MichaelJolley/number-one/blob/dev/CONTRIBUTING.md

**Comment by MichaelJolley** [comment]
Hola @exegete46! Did the link above cover what you're thinking?

**Comment by exegete46** [comment]
Apologies, your reply got lost in my emails somewhere.  I should have read through the CONTRIBUTING before opening a pull request, sorry.  

The documentation in CONTRIBUTING does address my concerns.  The reason I was looking for the information in the README, is that I was expecting it to be listed for someone using the app, rather than contributing.
