### ISSUE TITLE
Idea - allow users to customise their display name via chat 

### ISSUE THREAD

**Issue by cmjchrisjones** [builders-club/number-one#29]
How about allowing users in Twitch chat to customise their channel name in Fauna via a chat command?

**Comment by MichaelJolley** [comment]
The more I think about this I'm not sold on it.  Let's discuss.  Here are a few issues I've been thinking of:

- We update the user profile regularly so we'd need to have an additional field we use to hold this so it doesn't get overwritten.
- My biggest issue would be confusion. If your Twitch chat handle is foo but you set your name to bar, what do I call that person? Do I say "foo you're right" or "bar you're right"? I think it would be confusing for viewers (especially new viewers) to see a different name on screen than in chat.

Thoughts?

**Comment by MichaelJolley** [comment]
Closing as inactive
