### ISSUE TITLE
We should be securing our webhooks!

### ISSUE THREAD

**Issue by parithon** [builders-club/number-one#31]
As per the documentation, we should be using `hub.secret` in our payload to ensure the requests are genuine.

See https://dev.twitch.tv/docs/api/webhooks-reference#subscribe-tounsubscribe-from-events

Name|Type|Description
-|-|-
hub.secret | string | Secret used to sign notification payloads. The X-Hub-Signature header is generated by sha256 (secret, notification_bytes). We strongly encourage you to use this, so your application can verify that notifications are genuine.

**Comment by MichaelJolley** [comment]
Absolutely!

**Comment by MaryJoStaebler** [comment]
May I give webhooks the security blanket they need?

**Comment by MichaelJolley** [comment]
Go for it!

**Comment by MichaelJolley** [comment]
@allcontributors please add @MaryJoStaebler for code

**Comment by parithon** [comment]
This has merged!
