### ISSUE TITLE
CONTRIBUTING.md - SSL reference should be updated to builders-club

### ISSUE THREAD

**Issue by MaryJoStaebler** [builders-club/number-one#40]
**Describe the bug**
In the contributing documentations, the clone instructions for SSL reference MichaelJolley repo that is no longer there.  (It moved ya?)

**To Reproduce**
Look at contributing.md file

**Expected behavior**
git upstream line would be:
git remote add upstream git@github.com:builders-club/number-one

**Comment by MichaelJolley** [comment]
100%. Good catch. I bet our other repos have the same issue.

@allcontributors please add @MaryJoStaebler for bugs

**Comment by parithon** [comment]
This has merged!
