### ISSUE TITLE
Add !so from Vulcan

### ISSUE THREAD

**Issue by jwalter** [builders-club/number-one#88]
**Is your feature request related to a problem? Please describe.**
Add !so from [Vulcan ](https://github.com/MichaelJolley/vulcan) to enable shoutouts

**Describe the solution you'd like**
Copy pasta text from vulcan command into number-one architecture

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MichaelJolley** [comment]
@jwalter I re-opened these for now because they don't live in `main.`  They'll be auto-closed when we merge dev to main. I'm fixing a CD GH action before doing that. Hopefully I'll get it done today.
